version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: docs
      MONGO_INITDB_ROOT_PASSWORD: docs@123
    ports:
      - 27019:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
